CREATE TABLE journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    start_date DATE NOT NULL,
    end_date DATE,
    visibility VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_journals_visibility
      CHECK (visibility IN ('PRIVATE', 'FRIENDS', 'PUBLIC')),

    CONSTRAINT chk_journals_dates
      CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_journals_created_at ON journals(created_at);
CREATE INDEX IF NOT EXISTS idx_journals_start_date ON journals(start_date);
CREATE INDEX IF NOT EXISTS idx_journals_visibility ON journals(visibility);
