CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id BIGINT NOT NULL,

    entry_date DATE NOT NULL,
    title VARCHAR(200),
    content TEXT NOT NULL,
    mood VARCHAR(50),
    weather VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_journal_entries_journal
      FOREIGN KEY (journal_id)
      REFERENCES journals (id)
      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_journal_entries_journal_id ON journal_entries(journal_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_entry_date ON journal_entries(entry_date);
