create table account (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(50) NOT NULL,
                         amount DOUBLE NOT NULL
);